#!/usr/bin/php

<?php

use Cilex\Application;

include __DIR__ . '/vendor/autoload.php';

$app = new Application('CanIRunIt Console', '1.0');
//$app->command(new \Cilex\Command\GreetCommand());
$app->run();
