#!/usr/bin/env php

<?php

use Symfony\Component\Console\Application;
use App\Commands\CheckCommand;

require_once __DIR__ . '/vendor/autoload.php';

$app = new Application('CanIRunIt Console', '1.0');
$app->add(new CheckCommand());
$app->run();
